# Generated by Django 3.0.6 on 2020-05-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleandmeetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='people',
        ),
        migrations.AddField(
            model_name='person',
            name='visited_meetgins',
            field=models.ManyToManyField(to='peopleandmeetings.Meeting'),
        ),
    ]
