# Generated by Django 3.0.6 on 2020-05-30 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peopleandmeetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['meeting_name', '-date'], 'verbose_name': 'Встреча', 'verbose_name_plural': 'Встречи'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-competition_score', '-tests_score'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='sum_score',
        ),
    ]
