# Generated by Django 3.0.6 on 2020-05-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_category_ison'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category', '-isOn'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='question',
            name='isOn',
            field=models.BooleanField(default=True, verbose_name='Включить вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=50, verbose_name='Текст вопроса'),
        ),
    ]
