# Generated by Django 3.0.6 on 2020-05-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20200530_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-isOn', 'category'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
