# Generated by Django 3.0.6 on 2020-05-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20200530_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='isOn',
        ),
    ]
