# Generated by Django 3.0.6 on 2020-05-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.CharField(choices=[('Java', 'Java'), ('C++', 'C++')], default='C++', max_length=100),
        ),
    ]
