# Generated by Django 3.0.6 on 2020-05-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='categories',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.CharField(max_length=100, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Java', 'Java'), ('C++', 'C++')], default='C++', max_length=100, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
    ]
