# Generated by Django 3.0.6 on 2020-05-06 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200506_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Java', 'Java'), ('C++', 'C++')], default='Выберите тему', max_length=100, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='question',
            name='true_answer',
            field=models.CharField(default='Введите ответ', max_length=50, verbose_name='Правильный ответ'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='possibleanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
    ]
